/*
 * PanelListaSubTareas.java
 *
 * Created on June 20, 2007, 5:46 PM
 */

package com.spirit.timeTracker.gui.main;

/**
 *
 * @author  lmunoz
 */
public class PanelListaSubTareas extends javax.swing.JPanel {
    
    /** Creates new form PanelListaSubTareas */
    public PanelListaSubTareas() {
        initComponents();
    }
    
    public javax.swing.JPanel getPanelInformacion() {
        return panelInformacion;
    }
    
    public void setPanelInformacion(javax.swing.JPanel panelInformacion) {
        this.panelInformacion = panelInformacion;
    }
    
    public javax.swing.JScrollPane getSpanelSubTareas() {
        return spanelSubTareas;
    }
    
    public void setSpanelSubTareas(javax.swing.JScrollPane spanelSubTareas) {
        this.spanelSubTareas = spanelSubTareas;
    }
    
    public javax.swing.JTable getTblSubTareas() {
        return tblSubTareas;
    }
    
    public void setTblSubTareas(javax.swing.JTable tblSubTareas) {
        this.tblSubTareas = tblSubTareas;
    }
    
    public void setLblFechaCreacion(javax.swing.JLabel lblFechaCreacion) {
        this.lblFechaCreacion = lblFechaCreacion;
    }
    
    public javax.swing.JLabel getLblTituloDescripcion() {
        return lblTituloDescripcion;
    }
    
    public void setLblTituloDescripcion(javax.swing.JLabel lblTituloDescripcion) {
        this.lblTituloDescripcion = lblTituloDescripcion;
    }
    
    public javax.swing.JLabel getLblTituloFechaCreacion() {
        return lblTituloFechaCreacion;
    }
    
    public void setLblTituloFechaCreacion(javax.swing.JLabel lblTituloFechaCreacion) {
        this.lblTituloFechaCreacion = lblTituloFechaCreacion;
    }
    
    public javax.swing.JScrollPane getSpanelDescripcion() {
        return spanelDescripcion;
    }
    
    public void setSpanelDescripcion(javax.swing.JScrollPane spanelDescripcion) {
        this.spanelDescripcion = spanelDescripcion;
    }
    
    public javax.swing.JScrollPane getSpanelInformacion() {
        return spanelInformacion;
    }
    
    public void setSpanelInformacion(javax.swing.JScrollPane spanelInformacion) {
        this.spanelInformacion = spanelInformacion;
    }
    
    public void setTxtAreaDescripcion(javax.swing.JTextArea txtAreaDescripcion) {
        this.txtAreaDescripcion = txtAreaDescripcion;
    }
    
    
    
    public static javax.swing.JLabel getLblFechaCreacion() {
        return lblFechaCreacion;
    }
    
    public static javax.swing.JTextArea getTxtAreaDescripcion() {
        return txtAreaDescripcion;
    }

    public static javax.swing.JLabel getLblTipo() {
        return lblTipo;
    }

    public static void setLblTipo(javax.swing.JLabel aLblTipo) {
        lblTipo = aLblTipo;
    }

    public javax.swing.JLabel getLblTituloTipo() {
        return lblTituloTipo;
    }

    public void setLblTituloTipo(javax.swing.JLabel lblTituloTipo) {
        this.lblTituloTipo = lblTituloTipo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        spanelInformacion = new javax.swing.JScrollPane();
        panelInformacion = new javax.swing.JPanel();
        spanelDescripcion = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        lblTituloFechaCreacion = new javax.swing.JLabel();
        lblFechaCreacion = new javax.swing.JLabel();
        lblTituloDescripcion = new javax.swing.JLabel();
        lblTituloTipo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        spanelSubTareas = new javax.swing.JScrollPane();
        tblSubTareas = new javax.swing.JTable();

        

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(255, 255, 255));
        spanelInformacion.setMinimumSize(new java.awt.Dimension(23, 100));
        spanelInformacion.setPreferredSize(new java.awt.Dimension(100, 100));
        panelInformacion.setBackground(new java.awt.Color(255, 255, 255));
        panelInformacion.setMinimumSize(new java.awt.Dimension(100, 90));
        panelInformacion.setPreferredSize(new java.awt.Dimension(100, 90));
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtAreaDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setTabSize(3);
        spanelDescripcion.setViewportView(txtAreaDescripcion);

        lblTituloFechaCreacion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTituloFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloFechaCreacion.setText("Fecha Creacion:");

        lblFechaCreacion.setForeground(new java.awt.Color(153, 153, 153));

        lblTituloDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTituloDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloDescripcion.setText("Descripcion:");
        lblTituloDescripcion.setMaximumSize(new java.awt.Dimension(68, 14));
        lblTituloDescripcion.setPreferredSize(new java.awt.Dimension(68, 14));

        lblTituloTipo.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTituloTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloTipo.setText("Tipo:");
        lblTituloTipo.setMaximumSize(new java.awt.Dimension(27, 14));
        lblTituloTipo.setMinimumSize(new java.awt.Dimension(27, 14));
        lblTituloTipo.setPreferredSize(new java.awt.Dimension(27, 14));

        lblTipo.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(lblFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(spanelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spanelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );
        spanelInformacion.setViewportView(panelInformacion);

        add(spanelInformacion);

        tblSubTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Inicio", "Descripcion", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spanelSubTareas.setViewportView(tblSubTareas);

        add(spanelSubTareas);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblFechaCreacion;
    public static javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloDescripcion;
    private javax.swing.JLabel lblTituloFechaCreacion;
    private javax.swing.JLabel lblTituloTipo;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JScrollPane spanelDescripcion;
    private javax.swing.JScrollPane spanelInformacion;
    private javax.swing.JScrollPane spanelSubTareas;
    private javax.swing.JTable tblSubTareas;
    public static javax.swing.JTextArea txtAreaDescripcion;
    // End of variables declaration//GEN-END:variables
    
}
