package com.spirit.sri.gui.util;

public interface IfTablas {

	static int COLUMNA_IMAGEN_COMPRA = 0;
	static int COLUMNA_NUMERO_COMPRA = 1;
	static int COLUMNA_TIPO_IDENTIFICACION_COMPRA = 2;
	static int COLUMNA_PROVEEDOR_COMPRA = 3;
	static int COLUMNA_TIPO_COMPROBANTE_COMPRA = 4;
	static int COLUMNA_SERIE_SECUENCIAL_COMPRA = 5;
	static int COLUMNA_AUTORIZARION_COMPRA = 6;
	static int COLUMNA_FECHA_EMISION_COMPRA = 7;
	static int COLUMNA_BASE_CERO_COMPRA = 8;
	static int COLUMNA_BASE_GRAVADA_COMPRA = 9;
	static int COLUMNA_BASE_NO_OBJETO_IVA_COMPRA = 10;
	static int COLUMNA_MONTO_IVA_COMPRA = 11;
	

	static int COLUMNA_IMAGEN_VENTA = 0;
	static int COLUMNA_NUMERO_VENTA = 1;
	static int COLUMNA_CLIENTE_VENTA = 2;
	static int COLUMNA_TIPO_COMPROBANTE_VENTA = 3;
	static int COLUMNA_NUMERO_EMISIONES_VENTA = 4;
	static int COLUMNA_BASE_CERO_VENTA = 5;
	static int COLUMNA_BASE_GRAVADA_VENTA = 6;
	static int COLUMNA_IVA_VENTA = 7;
	static int COLUMNA_IVA_BIEN_VENTA = 8;
	static int COLUMNA_IVA_SERVICIO_VENTA = 9;
	
	static int COLUMNA_IMAGEN_ANULACION = 0;
	static int COLUMNA_NUMERO_ANULACION = 1;
	static int COLUMNA_TIPO_COMPROBANTE_ANULACION = 2;
	static int COLUMNA_ESTABLECIMIENTO_ANULACION = 3;
	static int COLUMNA_PUNTO_EMISION_ANULACION = 4;
	static int COLUMNA_SECUENCIAL_INICIAL_ANULACION = 5;
	static int COLUMNA_SECUENCIAL_FINAL_ANULACION = 6;
	static int COLUMNA_AUTORIZACION_ANULACION = 7;
	
}
