/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPBpmConsole.java
 *
 * Created on 31/05/2010, 03:35:16 PM
 */

package com.spirit.bpm.gui.panel;

import com.spirit.client.model.MantenimientoModelImpl;

/**
 *
 * @author Windows
 */
public abstract class JPBpmAdminConsole extends MantenimientoModelImpl {

    /** Creates new form JPBpmConsole */
    public JPBpmAdminConsole() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProcesosActivos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblProcesosTerminados = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFechaBamDesde = new javax.swing.JLabel();
        pnlProceso = new javax.swing.JTabbedPane();
        pnlInfoTarea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblIniciadoPor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblFechaUltimaAct = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFinalizadoPor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTiempoEjecucion = new javax.swing.JLabel();
        pnlDescripcion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        pnlComentarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstComentarios = new javax.swing.JList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlInstanciaProceso = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInstanciaProcesos = new javax.swing.JTable();
        chkPendientes = new javax.swing.JCheckBox();
        tbpnlTareas = new javax.swing.JTabbedPane();
        pnlTareas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        pnlProcesos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProcesos = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Procesos Activos");

        lblProcesosActivos.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblProcesosActivos.setText("XX");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Procesos Terminados:");

        lblProcesosTerminados.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblProcesosTerminados.setText("XX");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Desde: ");

        lblFechaBamDesde.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblFechaBamDesde.setText("XX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(lblProcesosActivos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaBamDesde))
                            .addComponent(lblProcesosTerminados))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblProcesosActivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblProcesosTerminados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblFechaBamDesde))
                .addGap(20, 20, 20))
        );

        pnlProceso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instancia de Proceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Fecha Inicio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Iniciado Por:");

        lblNombre.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblNombre.setText("XX");

        lblEstado.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblEstado.setText("XX");

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblFechaInicio.setText("XX");

        lblIniciadoPor.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblIniciadoPor.setText("XX");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Fecha Fin:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("Fecha Ultima Act.:");

        lblFechaUltimaAct.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblFechaUltimaAct.setText("XX");

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblFechaFin.setText("XX");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Finalizado Por:");

        lblFinalizadoPor.setFont(new java.awt.Font("Tahoma", 2, 11));
        lblFinalizadoPor.setText("XX");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tiempo Ejecucion:");

        lblTiempoEjecucion.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblTiempoEjecucion.setText("XX");

        javax.swing.GroupLayout pnlInfoTareaLayout = new javax.swing.GroupLayout(pnlInfoTarea);
        pnlInfoTarea.setLayout(pnlInfoTareaLayout);
        pnlInfoTareaLayout.setHorizontalGroup(
            pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoTareaLayout.createSequentialGroup()
                        .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(77, 77, 77)
                        .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(lblNombre)))
                    .addGroup(pnlInfoTareaLayout.createSequentialGroup()
                        .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTiempoEjecucion)
                            .addComponent(lblFinalizadoPor)
                            .addComponent(lblFechaUltimaAct)
                            .addComponent(lblFechaFin)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblIniciadoPor))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        pnlInfoTareaLayout.setVerticalGroup(
            pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblFechaUltimaAct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIniciadoPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblFinalizadoPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTiempoEjecucion))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pnlProceso.addTab("<html><b>Info</b></html>", pnlInfoTarea);

        txaDescripcion.setColumns(20);
        txaDescripcion.setEditable(false);
        txaDescripcion.setLineWrap(true);
        txaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txaDescripcion);

        javax.swing.GroupLayout pnlDescripcionLayout = new javax.swing.GroupLayout(pnlDescripcion);
        pnlDescripcion.setLayout(pnlDescripcionLayout);
        pnlDescripcionLayout.setHorizontalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDescripcionLayout.setVerticalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlProceso.addTab("<html><b>Descripcion</b></html>", pnlDescripcion);

        lstComentarios.setModel(new javax.swing.AbstractListModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstComentarios);

        javax.swing.GroupLayout pnlComentariosLayout = new javax.swing.GroupLayout(pnlComentarios);
        pnlComentarios.setLayout(pnlComentariosLayout);
        pnlComentariosLayout.setHorizontalGroup(
            pnlComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComentariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlComentariosLayout.setVerticalGroup(
            pnlComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComentariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlProceso.addTab("<html><b>Comentarios(0)</b></html>", pnlComentarios);

        tblInstanciaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Prioridad", "Proceso", "F. Inicio", "F. Esperada"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInstanciaProcesos);

        chkPendientes.setSelected(true);
        chkPendientes.setText("Activos");

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblTareas);

        javax.swing.GroupLayout pnlTareasLayout = new javax.swing.GroupLayout(pnlTareas);
        pnlTareas.setLayout(pnlTareasLayout);
        pnlTareasLayout.setHorizontalGroup(
            pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        pnlTareasLayout.setVerticalGroup(
            pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        tbpnlTareas.addTab("<html><b>Tareas(0)</b></html>", pnlTareas);

        javax.swing.GroupLayout pnlInstanciaProcesoLayout = new javax.swing.GroupLayout(pnlInstanciaProceso);
        pnlInstanciaProceso.setLayout(pnlInstanciaProcesoLayout);
        pnlInstanciaProcesoLayout.setHorizontalGroup(
            pnlInstanciaProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInstanciaProcesoLayout.createSequentialGroup()
                .addComponent(chkPendientes)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addComponent(tbpnlTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        pnlInstanciaProcesoLayout.setVerticalGroup(
            pnlInstanciaProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInstanciaProcesoLayout.createSequentialGroup()
                .addComponent(chkPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpnlTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("<html><b>Instancias</b></html>", pnlInstanciaProceso);

        tblProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblProcesos);

        javax.swing.GroupLayout pnlProcesosLayout = new javax.swing.GroupLayout(pnlProcesos);
        pnlProcesos.setLayout(pnlProcesosLayout);
        pnlProcesosLayout.setHorizontalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProcesosLayout.setVerticalGroup(
            pnlProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("<html><b>Procesos</b></html>", pnlProcesos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox chkPendientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JLabel lblEstado;
    protected javax.swing.JLabel lblFechaBamDesde;
    protected javax.swing.JLabel lblFechaFin;
    protected javax.swing.JLabel lblFechaInicio;
    protected javax.swing.JLabel lblFechaUltimaAct;
    protected javax.swing.JLabel lblFinalizadoPor;
    protected javax.swing.JLabel lblIniciadoPor;
    protected javax.swing.JLabel lblNombre;
    protected javax.swing.JLabel lblProcesosActivos;
    protected javax.swing.JLabel lblProcesosTerminados;
    protected javax.swing.JLabel lblTiempoEjecucion;
    protected javax.swing.JList lstComentarios;
    private javax.swing.JPanel pnlComentarios;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlInfoTarea;
    private javax.swing.JPanel pnlInstanciaProceso;
    protected javax.swing.JTabbedPane pnlProceso;
    private javax.swing.JPanel pnlProcesos;
    private javax.swing.JPanel pnlTareas;
    protected javax.swing.JTable tblInstanciaProcesos;
    protected javax.swing.JTable tblProcesos;
    protected javax.swing.JTable tblTareas;
    protected javax.swing.JTabbedPane tbpnlTareas;
    protected javax.swing.JTextArea txaDescripcion;
    // End of variables declaration//GEN-END:variables

}
