package com.spirit.nomina.handler;

public class NominaParametros {

	
	public static String TIPO_PARAMETRO = "NOMINA";
	
	public static String CODIGO_APORTE_IESS_PERSONAL = "APIESS";
	
	public static String CODIGO_SALARIO_MINIMO_VITAL = "SMV";
	
	public static String CODIGO_FONDO_RESERVA_PREDETERMINADO = "FONDORESERVAPREDETERMINADO";
	
	public static String REGISTRAR_IMPUESTO_RENTA_CON_VALOR_CERO = "REGISTRARIMPUESTORENTACERO";
	
	public static String CARGAR_CONTRATO_PLANTILLA_EN_CONTRATO_NUEVO = "CARGARCONTRATOPLANTILLA";
	
	public static String PARAMETRO_EMPRESA_BASE_CODIGO_SUELDO_BASICO = "BASECODIGOSUELDO";
	
	public static String BASE_CODIGO_FONDO_RESERVA_PARAMETRO_EMPRESA = "FR";
	
	public static String BASE_TIPOS_CONTRATOS_PARA_AUMENTAR_FONDO_RESERVA = "TCFR";
	
	public static String BASE_CODIGO_IMPUESTO_RENTA_PARAMETRO_EMPRESA = "IR";
	
	public static String BASE_CODIGO_TIPO_ROL_BENEFICIOS_SOCIALES_PARA_REPORTE = "BSR";
	
	public static String ANIO_UTILIDADES = "ANIOUTILIDADES";
	
	public static String USAR_FECHA_DIA_FINAL_ROL_PARA_CHEQUES = "USARFECHADIAFINALROLPARACHEQUES"; 
	
	
}
